# Generated by Django 6.0 on 2025-12-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "new_events_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество новый мероприятий"
                    ),
                ),
                (
                    "updated_events_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество обновленных мероприятий"
                    ),
                ),
            ],
        ),
    ]
