# Generated by Django 6.0 on 2025-12-16 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID площадки",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название площадки"),
                ),
            ],
            options={
                "verbose_name": "Площадка",
                "verbose_name_plural": "Площадки",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID мероприятия",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название площадки"),
                ),
                ("date", models.DateField(verbose_name="Дата проведения")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=6,
                        verbose_name="Статус мероприятия",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="events.place",
                        verbose_name="Место проведения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ["-date", "name"],
            },
        ),
    ]
